# Usamos una versión ligera de Node.js
FROM node:alpine

# Creamos el directorio de la app
WORKDIR /usr/src/app

# Copiamos el archivo de código
COPY index.js .

# Comando para arrancar la aplicación
CMD ["node", "index.js"]